services:
  backend:
    build:
      target: build
    command: npx tsx watch src/index.ts
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      target: build
    environment:
      NODE_ENV: development
    command: npm run dev
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/public:/app/public
      - ./frontend/components:/app/components
      - ./frontend/lib:/app/lib
      - ./frontend/__tests__:/app/__tests__
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/package.json:/app/package.json
      - ./frontend/jest.config.ts:/app/jest.config.ts
      - ./frontend/jest.setup.ts:/app/jest.setup.ts
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
